fixing errors

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,26 @@
 #!/usr/bin/env bash
-# transfers a file from a client to a server with scp
 
-if [ "$#" -lt 3 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -otrictHostKeyChecking=no "$1" "$3@$2":~/
+# Check if correct number of parameters are provided
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY_PATH=$4
+
+# Construct theCP command
+scp_command="scp -otrictHostKeyChecking=no -i $SSH_KEY_PATH $FILE_PATH $USERNAME@$SERVER_IP:~/"
+
+# Execute theCP command
+$scp_command
+
+# Check if theCP command was successful
+if scp -otrictHostKeyChecking=no -i "$PATH_TO_FILE" "$USERNAME"@"$IP":~/; then
+    echo "File transferred successfully TO $USERNAME@$IP:~/"
 else
-	scp -i "$4" -otrictHostKeyChecking=no "$1" "$3@$2":~/
+    echo "Error transferring file."
 fi
